#!/bin/sh

#
# Initialize submodules:
#
# AVL submodule
# NF  submodule (protocol tests)
#
git submodule init
git submodule update

#
# bmp
# 
gcc -g -Wall -o bmp  \
 src/bgp_peer.c      \
 src/bgp_router.c    \
 src/bmp_server.c    \
 src/bmp_session.c   \
 src/bmp_table.c     \
 src/bmp_recv.c      \
 src/bmp_process.c   \
 src/bmp_command.c   \
 src/bmp_context.c   \
 src/bmp_control.c   \
 src/bmp_show.c      \
 src/bmp_timer.c     \
 src/bmp_log.c       \
 src/bmp_debug.c     \
 src/bmp_config.c    \
 src/bmp_util.c      \
 src/bmp_main.c      \
-Iinclude            \
 lib/avl/src/*.c     \
-Ilib/avl/include/   \
 lib/msgchunk/*.c    \
-Ilib/msgchunk/      \
 lib/radix/*.c       \
-Ilib/radix/         \
-lpthread


rc=`echo $?`
#
# Append 'pwd' to path so that users can simply run 'bmp' instead of './bmp'
#
PATH=$PATH:$(pwd)
return $rc
