#!/bin/sh

#
# Initialize the Git submodules
#
#if [ $($ls lib/avl) ]; then
#  : 
#else
  git submodule init
  git submodule update
#fi     

OPTS='-O3 -fpack-struct -Wall'

#
# bmp
# 
gcc $OPTS -o bmp      \
 src/bmp_server.c     \
 src/bmp_client.c     \
 src/bmp_peer.c       \
 src/bmp_protocol.c   \
 src/bmp_command.c    \
 src/bmp_control.c    \
 src/bmp_timer.c      \
 src/bmp_util.c       \
 src/bmp_main.c       \
-Iinclude             \
 lib/avl/src/*.c      \
-Ilib/avl/include/

PATH=$PATH:$(pwd)

