#!/bin/sh

#
# Initialize submodules:
#
# AVL submodule
# NF  submodule (protocol tests)
#
git submodule init
git submodule update

#
# bmp
# 
gcc -g -fpack-struct -Wall -o bmp \
 src/bmp_server.c    \
 src/bmp_client.c    \
 src/bmp_peer.c      \
 src/bmp_protocol.c  \
 src/bmp_command.c   \
 src/bmp_control.c   \
 src/bmp_timer.c     \
 src/bmp_util.c      \
 src/bmp_main.c      \
-Iinclude            \
 lib/avl/src/*.c     \
-Ilib/avl/include/

#
# Append 'pwd' to path so that users can simply run 'bmp' instead of './bmp'
#
PATH=$PATH:$(pwd)

